spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_manegement_db
spring.datasource.username=postgres
spring.datasource.password=0000

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update